### ISSUE TITLE
Issue with chimeric.out files

### ISSUE THREAD

**Issue by RosannahCameron** [LosicLab/starchip#12]
Hi there,

I've just started using STARchip with the latest version of STAR (2.6.0a) and running into an issue as I don't seem to have a chimeric.out.sam file produced. I can generate the chimeric.out.sam with --chimOutType SeparateSAMold but then the chimeric.out.junctions file isn't created. I can run STAR twice to generate both files but I was wondering if there is a better solution?

**Comment by kippakers** [comment]
Hi Rosannah,

Thanks for using STARChip!  Thanks also for bringing this to my attention--I hadn't seen this change yet.  I don't see a better way at the moment, but I've put in a message to the STAR developer ([here](https://groups.google.com/forum/#!topic/rna-star/3VI8SOvX5GU)) , he may know a trick or be willing to implement an option for me.  Otherwise, I'll have to implement some large-ish changes to STARChip.  For now, I recommend running STAR twice, or using an older version of STAR.  

Thanks,
Kipp

**Comment by kippakers** [comment]
Looks like Alex has an updated STAR 2.6.0c with the ability to use the option:  --chimOutType Junctions SeparateSAMold , which should solve your issue.  Thanks again for bringing this to our attention!

**Comment by RosannahCameron** [comment]
Thanks for addressing this Kipp (and Alex)! Just a side note when I ran STAR twice to generate the junction and sam files I also needed to use sort the files with -V. I assume the fix you mentioned can generate two files that will be sorted the same way.
