### ISSUE TITLE
new troubles

### ISSUE THREAD

**Issue by ChrisLou-bioinfo** [LosicLab/starchip#13]
creating circRNA fasta and gtf for re-alignment and quantification
[W::fai_fetch] Reference 0:89-177 not found in FASTA file, returning empty sequence
Failed to fetch sequence in 0:89-177
[W::fai_fetch] Reference 0:0-88 not found in FASTA file, returning empty sequence
Failed to fetch sequence in 0:0-88
[W::fai_fetch] Reference 8:619295-629295 not found in FASTA file, returning empty sequence
Failed to fetch sequence in 8:619295-629295
[W::fai_fetch] Reference 8:0-10000 not found in FASTA file, returning empty sequence

**Comment by kippakers** [comment]
Dear ChrisLou,

Thanks for using STARChip.  Please rather than opening several issues, stick to one thread (all of your problems are related), and respond to my attempts to help you.  

As with before, we are getting some nonsense circRNA locations.  For example, 0:0-88 or as before 8680r7 for a circRNA position.  

The list of discovered circRNA should be at rawdata/cRNA.cutoff.5 .  Can you confirm there are circRNA in that file that do not fit appear correct?  My best guess right now is that there is a special character that is being treated differently and causing STARChip to incorrectly read a circRNA.   What operating system are you working on?

Thanks,
Kipp

**Comment by ChrisLou-bioinfo** [comment]
operating system: CentOS 7.3 64-bit
STAR_2.5.3a
perl v5.16.1
bedtools v2.26.0
R  3.4.4
index :gencode.v28.primary_assembly.annotation.gtf 
genome.fa:GRCh38.primary_assembly.genome.fa

**Comment by kippakers** [comment]
Thanks.  Can you send me the file rawdata/cRNA.cutoff.5 or rawdata/circs5.1.investigate.IDs

Send it to nicholas.kipp.akers@gmail.com please.
